default:
  outputs:
    dev:
      dbname: dev
      host: redshiftcluster-yqg3f7wh5cn2.ckkbrfwpeewq.eu-west-2.redshift.amazonaws.com
      password: o3h5ooFwP9ykoNwe
      port: 5439
      schema: public
      threads: 4
      type: redshift
      user: awsuser
  target: dev